apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pydxkj4qc-go 
  janus-idp.io/tekton: pydxkj4qc-go
  backstage.io/kubernetes-id: pydxkj4qc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pydxkj4qc-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml