apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pydxkj4qc-go
  janus-idp.io/tekton: pydxkj4qc-go
  backstage.io/kubernetes-id: pydxkj4qc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pydxkj4qc-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
